apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
      - name: html-site
        image: nandhutk/html-css-site:latest
        ports:
        - containerPort: 80
---

