apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-site-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-site
  template:
    metadata:
      labels:
        app: html-site
    spec:
      containers:
      - name: html-site
        image: nandhutk/html-css-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-site-service
spec:
  type: NodePort
  selector:
    app: html-site
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
